server:
  port: 8002
spring:
  application:
    name: microservice-product-service
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management.security.enabled: false
endpoints.health.sensitive: false

info:
  author: daizhifeng
  app:
    name: microservice-product-service
    version: 0.0.1-SNAPSHOT

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*" #暴露所有端点 默认是info,health
