server:
  port: 8080
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/daizf/spring-cloud-config-repo.git        # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

#http请求地址和资源文件映射如下:，可参考
#    /{application}/{profile}[/{label}]
#    /{application}-{profile}.yml
#    /{label}/{application}-{profile}.yml
#    /{application}-{profile}.properties
#    /{label}/{application}-{profile}.properties
#    /{label}/{application}-{profile}.properties