server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: microservice-user-service,microservice-order-service
  clusterNameExpression: "'default'"